-
  name: vim
  files:
    vimrc:
      - ~/.vimrc
  folders:
    vim:
      - ~/.vim
  postconf_hook:
    - post-install-hook.sh
-
  name: tmux
  files:
    tmux.conf:
      - ~/.tmux.conf
-
  name: zsh
  files:
    zshrc:
      - ~/.zshrc
  folders:
    zsh:
      - ~/.zsh
    preconf_hook:
      - pre-install-hook.sh
-
  name: git
  files:
    gitconfig:
      - ~/.gitconfig
-
  name: termite
  files:
    config:
      - ~/.config/termite/config
-
  name: mpd
  files:
    mpd.conf:
      - ~/.config/mpd/mpd.conf
-
  name: ncmpcpp
  folders:
    ncmpcpp:
      - ~/.ncmpcpp
-
  name: sway
  folders:
    sway:
      - ~/.config/sway

# name: program + folder
# files:
#   file_in_folder:
#       - target files
# folders:
#   folder_in_folder:
#       - target folder
# preconf_hook: script_in_Folder
# postconf_hook: script_in_folder
