- name: vim
  depends:
    default:
      - vim
      - fzf
      - the_silver_searcher
  postconf_hook:
    - vim-post-install.sh

- name: tmux
  depends:
    default: tmux

- name: zsh
  depends:
    default:
      - fd
      - fzf
      - the_silver_searcher
      - zsh
      - zsh-syntax-highlighting

- name: git
  depends:
    default:
      - git
      - vim

- name: termite
  depends:
    default: termite

- name: mpd
  depends:
    default:
      - mpd
      - mpc
      - cantata

- name: ncmpcpp
  depends:
    default: ncmpcpp

- name: sway
  depends:
    default:
      - sway
      - playerctl
      - sysstat
      - pamixer
      - otf-font-awesome
      - perl-mimeinfo
      - jq
      - udiskie
      - imagemagick
    aur:
      - brillo
      - slurp
      - grim
      - mako
      - waybar

- name: ranger
  depends:
    default:
      - ranger
      - atool

- name: ghc

- name: system
  depends:
    default:
      - asciiquarium
      - audacity
      - calibre
      - chromium
      - cmatrix
      - cowsay
      - eog
      - firefox
      - gimp
      - htop
      - libreoffice-fresh
      - libreoffice-fresh-de
      - libreoffice-fresh-en-gb
      - libqalculate
      - mcomix
      - mpv
      - texlive-most
      - vlc
      - zathura
      - zathura-cb
      - zathura-pdf-mupdf
      - unzip
      - unrar
      - wget

- name: autostart
  depends:
    default:
      - udiskie

# name: program + folder
# depends:
#   default:
#       - names
#   distro:
#       - names
# preconf_hook: script_in_Folder
# postconf_hook: script_in_folder
