- name: vim
  depends:
    default:
      - vim
      - fzf
  postconf_hook:
    - vim-post-install.sh

- name: tmux
  depends:
    default: tmux

- name: zsh
  depends:
    default:
      - zsh
      - zsh-syntax-highlighting
      - fzf

- name: git
  depends:
    default: git

- name: termite
  depends:
    default: termite

- name: mpd
  depends:
    default:
      - mpd
      - mpc

- name: ncmpcpp
  depends:
    default: ncmpcpp

- name: sway
  depends:
    default:
      - sway
      - pamixer

- name: system
  depends:
    default:
      - asciiquarium
      - audacity
      - calibre
      - chromium
      - cmatrix
      - cowsay
      - firefox
      - gimp
      - htop
      - libreoffice-fresh
      - libreoffice-fresh-de
      - libreoffice-fresh-en-gb
      - mcomix
      - mpv
      - vlc
      - zathura

# name: program + folder
# depends:
#   default:
#       - names
#   distro:
#       - names
# preconf_hook: script_in_Folder
# postconf_hook: script_in_folder
